package "convertsequest"
version "@PACKAGE_VERSION@"
purpose "Converts a mzIdentML file (generated by Sequest) to the percolator_in XML format"

option "target-file" t "A target file in mzIdentML (sequest) format" string typestr="filename" optional multiple
option "decoy-file" d "A decoy file in mzIdentML (sequest) format" string typestr="filename" optional multiple
option "enzyme-type" e "Type of enzyme" values="no_enzyme","elastase","chymotrypsin","trypsin" default="trypsin" enum optional
option "tmp-file-for-indermediate-results" w "tmp file for indermediate results"  string default="/tmp/convertsequest-tmpfile.tcb" optional

option "ptm" b  "Calculate feature for number of post-translational modifications" flag off 
option "pngasef" N "Calculate feature based on N-linked glycosylation pattern resulting from a PNGaseF treatment. (N[*].[ST])" flag off
option "aa-freq" a "Calculate amino acid frequency features" flag off

