find_path(GTEST_INCLUDE_DIR gtest)
find_library(GTEST_LIBRARIES NAMES libgtest.a)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Gtest DEFAULT_MSG GTEST_LIBRARIES GTEST_INCLUDE_DIR)
