name: Build and push percolator container image
on: workflow_dispatch
jobs:
  build_push_container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - name: percolator
            percolator_cmake_args: " "
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run docker/setup-qemu-action
        uses: docker/setup-qemu-action@v3
      - name: Run docker/setup-buildx-action
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: List available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Run docker/login-action
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run docker/metadata-action
        id: metadata_action_id
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/percolator/${{ matrix.name }}
          flavor: |
            latest=auto
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.title=percolator
            org.opencontainers.image.description=Semi-supervised learning for peptide identification from shotgun proteomics datasets
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.metadata_action_id.outputs.tags }}
          labels: ${{ steps.metadata_action_id.outputs.labels }}
          build-args: |
           "percolator_cmake_args=${{ matrix.percolator_cmake_args }}"
