name: Unified Build

on: 
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: preinstall
      run: sudo apt-get update && sudo apt-get install -y -o Acquire::Retries=3 libxml2-utils
    - name: create_dirs
      run: mkdir -p ${{ github.workspace }}/../release ${{ github.workspace }}/../build
    - name: configure_and_make
      run: ./admin/builders/ubuntu64_build.sh -s ${{ github.workspace }}/.. -r ${{ github.workspace }}/../release -b ${{ github.workspace }}/../build
    - name: unit_tests
      run: cd ${{ github.workspace }}/../build/percolator && sudo make install && make test ARGS="-V"
    # legacy build.yml behaviour
    - name: system_test  
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      run: cd ../build/percolator && sudo make install && make test-install
    # triggered_build.yml behaviour
    - name: zip raw binary
      if: github.event_name == 'workflow_dispatch'
      run: zip -j ${{ github.workspace }}/../release/percolator-noxml-ubuntu-portable.zip ${{ github.workspace }}/../build/percolator-noxml/src/percolator
    - name: Upload packages
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-packages
        path: ${{ github.workspace }}/../release

  build-ubuntu-arm:
    runs-on: ubuntu-22.04-arm
    steps:
    - uses: actions/checkout@v4
    - name: preinstall
      run: sudo apt-get update && sudo apt-get install -y -o Acquire::Retries=3 libxml2-utils
    - name: create_dirs
      run: mkdir -p ${{ github.workspace }}/../release ${{ github.workspace }}/../build
    - name: configure_and_make
      run: ./admin/builders/ubuntu64_build.sh -s ${{ github.workspace }}/.. -r ${{ github.workspace }}/../release -b ${{ github.workspace }}/../build
    - name: unit_tests
      run: cd ${{ github.workspace }}/../build/percolator && sudo make install && make test ARGS="-V"
    # legacy build.yml behaviour
    - name: system_test  
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      run: cd ../build/percolator && sudo make install && make test-install
    # triggered_build.yml behaviour
    - name: zip raw binary
      if: github.event_name == 'workflow_dispatch'
      run: zip -j ${{ github.workspace }}/../release/percolator-noxml-ubuntu-portable-arm64.zip ${{ github.workspace }}/../build/percolator-noxml/src/percolator
    - name: Upload packages
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-arm-packages
        path: ${{ github.workspace }}/../release

  build-osx:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v4
    - name: create_dirs
      run: mkdir -p ${{ github.workspace }}/../release ${{ github.workspace }}/../build
    - name: configure_and_make
      run: ./admin/builders/osx64_build.sh -s ${{ github.workspace }}/.. -r ${{ github.workspace }}/../release -b ${{ github.workspace }}/../build
    - name: unit_tests
      run: cd ${{ github.workspace }}/../build/percolator && sudo make install && make test ARGS="-V"
    # legacy build.yml behaviour
    - name: system_test
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      run: cd ../build/percolator && sudo make install && make test-install
    # triggered_build.yml behaviour
    - name: zip raw binary
      if: github.event_name == 'workflow_dispatch'
      run: zip ${{ github.workspace }}/../release/percolator-noxml-osx-portable.zip ${{ github.workspace }}/../build/percolator-noxml/src/percolator
    - name: Upload packages
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: osx-packages
        path: ${{ github.workspace }}/../release

  build-osx-arm:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: create_dirs
      run: mkdir -p ${{ github.workspace }}/../release ${{ github.workspace }}/../build
    - name: configure_and_make
      run: ./admin/builders/osx64_build.sh -s ${{ github.workspace }}/.. -r ${{ github.workspace }}/../release -b ${{ github.workspace }}/../build
    - name: unit_tests
      run: cd ${{ github.workspace }}/../build/percolator && sudo make install && make test ARGS="-V"
    # legacy build.yml behaviour
    - name: system_test
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      run: cd ../build/percolator && sudo make install && make test-install
    # triggered_build.yml behaviour
    - name: zip raw binary
      if: github.event_name == 'workflow_dispatch'
      run: zip ${{ github.workspace }}/../release/percolator-noxml-osx-portable-arm64.zip ${{ github.workspace }}/../build/percolator-noxml/src/percolator
    - name: Upload packages
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: osx-arm-packages
        path: ${{ github.workspace }}/../release

  build-windows:
    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v4
    - name: create_dirs
      run: MKDIR %GITHUB_WORKSPACE%\..\my_rel %GITHUB_WORKSPACE%\..\my_build
    - name: configure_and_make
      run: |
        CD %GITHUB_WORKSPACE%
        SET base_dir=%cd%
        ECHO %base_dir%
        CALL percolator\admin\builders\nativew64_build.bat -s %base_dir% -r %GITHUB_WORKSPACE%\..\my_rel -b %GITHUB_WORKSPACE%\..\my_build
    # triggered_build.yml behaviour
    - name: zip raw binary
      if: github.event_name == 'workflow_dispatch'
      shell: pwsh
      run: Compress-Archive -Path "${env:GITHUB_WORKSPACE}\..\my_build\percolator-noxml\src\Release\*.exe" -DestinationPath "${env:GITHUB_WORKSPACE}\..\my_rel\percolator-noxml-windows-portable.zip"
    - name: Upload packages
      if: github.event_name == 'workflow_dispatch'  
      uses: actions/upload-artifact@v4
      with:
        name: windows-packages
        path: ${GITHUB_WORKSPACE}\..\my_rel\percolator-noxml-windows-portable.zip
